name: CI-SharedAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List available Xcode versions
        run: |
          xcode-select -p
          xcodebuild -version

    - name: List available simulators
        run: |
          xcrun simctl list devices
    
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build and Test
        run: |
          xcodebuild test \
          -project SharedAPI.xcodeproj \
          -scheme SharedAPI \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=15.6' \
          CODE_SIGNING_ALLOWED=NO

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            TestResults
            ~/Library/Logs/scan/*.log

      - name: Capture Detailed Logs
        if: failure()
        run: |
          echo "Capturing detailed build logs..."
          find ~/Library/Logs/scan -type f -name "*.log"
          find ~/Library/Logs/xcodebuild -type f -name "*.log"

